// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0G9cIzYkNmFal7cJSMFaoib_sc752BSE',
    appId: '1:229323836948:web:891a545bbddec3b32fe101',
    messagingSenderId: '229323836948',
    projectId: 'flutter-web-push-test-3fb94',
    authDomain: 'flutter-web-push-test-3fb94.firebaseapp.com',
    storageBucket: 'flutter-web-push-test-3fb94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKgjGNm___CTdOG9lrSCdvhB-iHDOLTYs',
    appId: '1:229323836948:android:4a40ea4a39876f912fe101',
    messagingSenderId: '229323836948',
    projectId: 'flutter-web-push-test-3fb94',
    storageBucket: 'flutter-web-push-test-3fb94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP8VaJF075TbNC1cIwXxkkfihccbQ8-Xo',
    appId: '1:229323836948:ios:00c9987059f8de752fe101',
    messagingSenderId: '229323836948',
    projectId: 'flutter-web-push-test-3fb94',
    storageBucket: 'flutter-web-push-test-3fb94.appspot.com',
    iosClientId: '229323836948-br6bu6u1r1e4oauecmqdrs616rvd1o1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWebTest2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP8VaJF075TbNC1cIwXxkkfihccbQ8-Xo',
    appId: '1:229323836948:ios:00c9987059f8de752fe101',
    messagingSenderId: '229323836948',
    projectId: 'flutter-web-push-test-3fb94',
    storageBucket: 'flutter-web-push-test-3fb94.appspot.com',
    iosClientId: '229323836948-br6bu6u1r1e4oauecmqdrs616rvd1o1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWebTest2',
  );
}
